# Generated by Django 2.2.13 on 2022-06-12 16:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GradeAssignment',
            new_name='GradedAssignment',
        ),
    ]
